In [66]:
# 1. Import all necessary libraries and packages ||
import numpy as np
import pandas as pd
from pathlib import Path

In [69]:
# 2. Read the data files into dataframes from the extracted raw data folder
df_matches = pd.read_csv("../data/raw/matches.csv")
df_teams = pd.read_csv("../data/raw/teams.csv")
df_tournaments = pd.read_csv("../data/raw/tournaments.csv")

print(f"Matches Data is loaded with entries: {df_matches.shape}")
print(f"Teams Data is loaded with entries: {df_teams.shape}")
print(f"Tournaments Data is loaded with entries: {df_tournaments.shape}")

Matches Data is loaded with entries: (1068, 28)
Teams Data is loaded with entries: (537, 16)
Tournaments Data is loaded with entries: (23, 4)

In [72]:
print(f"Matches columns: {df_matches.columns}")
print(f"Teams columns: {df_teams.columns}")
print(f"Tournaments columns: {df_tournaments.columns}")

Matches columns: Index(['id', 'date', 'kickoff', 'stage', 'homeTeam', 'awayTeam', 'homeScore',
       'awayScore', 'result', 'extraTime', 'penalties', 'stadium', 'stadiumId',
       'city', 'attendance', 'referee', 'weather', 'stageNormalized',
       'tournament_year', 'captains', 'goals', 'penaltyShootout', 'matchNo',
       'kickoffUtc', 'timezone', 'homeRef', 'awayRef', 'country'],
      dtype='str')
Teams columns: Index(['name', 'code', 'iso', 'confederation', 'groupStage', 'knockoutPath',
       'finalPosition', 'coach', 'captain', 'squad', 'flag', 'tournament_year',
       '_squadFinalizedBy', 'squadKind', 'squadFetched',
       '_squadIsPreliminary'],
      dtype='str')
Tournaments columns: Index(['year', 'host', 'champion', 'file'], dtype='str')

In [ ]:
# 2. Feature Engineering: Combining tables with relevant fields that will enable strong predicting basics

df_matches = df_matches.merge(
    df_tournaments,
    left_on="tournament_year",
    right_on="year",
    how="left"
)
df_matches.head()

,id,date,kickoff,stage,homeTeam,awayTeam,homeScore,awayScore,result,extraTime,...,champion_x,file_x,year_y,host_y,champion_y,file_y,year,host,champion,file
0,1930-001,1930-07-13,15:00,group_1,France,Mexico,4.0,1.0,4-1,False,...,Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json
1,1930-002,1930-07-15,16:00,group_1,Argentina,France,1.0,0.0,1-0,False,...,Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json
2,1930-003,1930-07-16,14:45,group_1,Chile,Mexico,3.0,0.0,3-0,False,...,Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json
3,1930-004,1930-07-19,12:50,group_1,Chile,France,1.0,0.0,1-0,False,...,Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json
4,1930-005,1930-07-19,15:00,group_1,Argentina,Mexico,6.0,3.0,6-3,False,...,Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json,1930,['Uruguay'],Uruguay,tournaments/1930.json

In [82]:
# 3. Select important features from Teams

team_features = df_teams[
    [
        "name",
        "confederation",
        "finalPosition",
        "coach",
        "captain",
        "tournament_year"
    ]

]
team_features.tail()

,name,confederation,finalPosition,coach,captain,tournament_year
532,Colombia,CONMEBOL,NaN,"{'name': 'Néstor Lorenzo', 'country': 'Argenti...",NaN,2026
533,England,UEFA,NaN,"{'name': 'Thomas Tuchel', 'country': 'Germany'...",NaN,2026
534,Croatia,UEFA,NaN,"{'name': 'Zlatko Dalić', 'country': 'Croatia',...",NaN,2026
535,Ghana,CAF,NaN,"{'name': 'Otto Addo', 'country': 'Ghana', 'bor...",NaN,2026
536,Panama,Concacaf,NaN,"{'name': 'Thomas Christiansen', 'country': 'Sp...",NaN,2026